# Generated by Django 3.0 on 2022-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20220227_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='image/'),
        ),
    ]
